---
name: GO tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        golang: [1.16]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.golang }}
      - name: Cache Dependencies
        uses: actions/cache@dhadka/update-1.0.7
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-v2-${{ matrix.golang }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-v2-${{ matrix.golang }}-
      - name: Run tests
        run: make test
